name: 'commitlint-cli-action'
author: 'Dafnik'
description: 'A simple GitHub action to run @commitlint/cli checks.'
branding:
  icon: 'git-commit'
  color: 'purple'

inputs:
  commitlint_version:
    description: 'The version of commitlint to install'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Cache commitlint
      id: cache-commitlint
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-commitlint-cache@${{ inputs.commitlint_version }}

    - name: Installing commitlint
      shell: bash
      run: npm install --global commitlint@${{ inputs.commitlint_version }} @commitlint/config-conventional

    - name: Validate current commit (last commit) with commitlint
      shell: bash
      if: github.event_name == 'push'
      run: commitlint --from HEAD~1 --to HEAD --verbose

    - name: Validate PR commits with commitlint
      shell: bash
      if: github.event_name == 'pull_request'
      run: commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
